const $ = id => document.getElementById(id);
const video=$('video'),img=$('image'),sourceCanvas=$('sourceCanvas'),sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true}),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const file=$('file'),drop=$('drop'),readout=$('readout'),controls=$('controls'),placeholder=$('placeholder');
const master=$('master'),macroA=$('macroA'),macroB=$('macroB'),bpm=$('bpm'),quality=$('quality'),fxSeed=$('fxSeed');
const promptEl=$('prompt'),genMode=$('genMode'),genEngine=$('genEngine'),genMotion=$('genMotion'),seedEl=$('seed'),genW=$('genW'),genH=$('genH'),cellSize=$('cellSize'),genSpeed=$('genSpeed');
const seedRead=$('seedRead'),fpsRead=$('fpsRead'),recordRead=$('recordRead');

const defaults={
  scale:.72,fps:45,bright:0,contrast:0,sat:0,hue:0,invert:false,gray:false,
  rgb:0,angle:0,poster:0,bits:8,noise:0,pixel:1,sort:0,blocks:0,blockSize:40,blockDrift:80,
  scan:0,wobble:0,wobbleFreq:8,wave:2,edge:0,half:0,ascii:0,solar:0,melt:0,shred:0,
  kaleido:0,tiles:0,vignette:0,mirror:false,strobe:0,strobeRate:8,glow:0,emboss:0,duotone:0,
  bands:0,bandSpeed:2,tunnel:0,prism:0,ghost:0,echo:0,ripples:0,rippleFreq:8,scratch:0,
  posterBurn:0,blockInvert:0,lineOffset:0,chromaNoise:0,dither:0,threshold:0,displace:0,feedbackZoom:0,datamosh:0
};
const ranges={
  scale:[.12,1,.01],fps:[1,60,1],bright:[-120,120,1],contrast:[-120,140,1],sat:[-100,360,1],hue:[-180,180,1],
  rgb:[0,120,1],angle:[0,360,1],poster:[0,16,1],bits:[1,8,1],noise:[0,180,1],pixel:[1,80,1],sort:[0,100,1],
  blocks:[0,140,1],blockSize:[4,260,1],blockDrift:[0,360,1],scan:[0,100,1],wobble:[0,120,1],wobbleFreq:[1,70,.1],wave:[-40,40,.1],
  edge:[0,100,1],half:[0,40,1],ascii:[0,32,1],solar:[0,255,1],melt:[0,100,1],shred:[0,100,1],kaleido:[0,12,1],tiles:[0,12,1],
  vignette:[0,100,1],strobe:[0,100,1],strobeRate:[1,60,.1],glow:[0,100,1],emboss:[0,100,1],duotone:[0,100,1],bands:[0,100,1],
  bandSpeed:[-20,20,.1],tunnel:[0,100,1],prism:[0,100,1],ghost:[0,100,1],echo:[0,98,1],ripples:[0,120,1],rippleFreq:[1,60,.1],
  scratch:[0,100,1],posterBurn:[0,100,1],blockInvert:[0,100,1],lineOffset:[0,120,1],chromaNoise:[0,100,1],dither:[0,100,1],threshold:[0,255,1],
  displace:[0,80,1],feedbackZoom:[0,12,.1],datamosh:[0,100,1]
};
const groups=[
  ['Render',['scale','fps']],
  ['Color',['bright','contrast','sat','hue','invert','gray','solar','duotone','posterBurn','threshold','dither']],
  ['Channel / glitch',['rgb','angle','chromaNoise','poster','bits','noise','pixel','sort','blocks','blockSize','blockDrift','blockInvert','datamosh']],
  ['Geometry',['wobble','wobbleFreq','wave','ripples','rippleFreq','displace','lineOffset','mirror','kaleido','tiles','melt','shred']],
  ['Print / neon',['edge','glow','emboss','half','ascii','scan','scratch','bands','bandSpeed','vignette','strobe','strobeRate']],
  ['Optical recursion',['tunnel','prism','ghost','echo','feedbackZoom']]
];
const presets={
  clean:{},xerox:{gray:true,contrast:80,poster:2,noise:20,scratch:25,dither:35},neon:{edge:90,glow:60,sat:180,rgb:18,scan:20},
  acid:{sat:260,hue:80,poster:6,kaleido:5,strobe:15,bands:50,prism:30},cctv:{gray:true,contrast:34,bright:-12,noise:38,scan:65,vignette:55,scratch:35},
  mosh:{poster:7,bits:5,rgb:18,blocks:22,sort:12,melt:20,echo:65,ghost:35,datamosh:45},ascii:{ascii:13,contrast:40,edge:20},
  thermal:{poster:8,sat:300,hue:-90,solar:120,noise:15,duotone:60},poster:{poster:5,half:14,contrast:25,sat:60,posterBurn:45,dither:20},
  fracture:{shred:55,blocks:45,blockDrift:180,rgb:24,tiles:4,blockInvert:50,displace:28},ritual:{kaleido:8,hue:120,edge:55,glow:45,vignette:42,tunnel:32},
  dirty:{contrast:18,sat:-18,rgb:9,noise:24,scan:55,wobble:7,vignette:38,scratch:45,lineOffset:30},
  databend:{datamosh:78,blocks:36,blockDrift:210,sort:24,rgb:25,noise:14,shred:26,echo:52},
  feedback:{echo:82,feedbackZoom:4.2,ghost:28,prism:20,tunnel:18,sat:35},
  terminal:{ascii:10,gray:true,contrast:75,threshold:115,scan:25,duotone:28},
  dream:{glow:78,ghost:42,echo:70,feedbackZoom:1.4,sat:55,hue:24,ripples:9,prism:12}
};

let s={...defaults},base={...defaults},rate={},lfo={},sweep={},groupEnabled={},keyGroup={};
let media='none',inputMedia='none',ready=false,playing=false,last=0,lastDraw=0,frame=0,started=false,drawFps=0,fpsWindow=performance.now(),fpsFrames=0;
let tmp=document.createElement('canvas'),tctx=tmp.getContext('2d',{willReadFrequently:true}),fx=document.createElement('canvas'),fctx=fx.getContext('2d',{willReadFrequently:true}),echo=document.createElement('canvas'),ectx=echo.getContext('2d',{willReadFrequently:true});
let undoStack=[],fxRandom=Math.random,recorder=null,recordChunks=[];

function label(k){return k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function byte(v){return clamp(v,0,255)}
function paramStep(k){return ranges[k]?ranges[k][2]:1}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return h>>>0}
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rnd(){return fxRandom()}
function coordNoise(x,y,z=0){const n=hash32(`${seedEl.value}|${promptEl.value}|${x}|${y}|${z}`);return(n>>>0)/4294967295}
function download(name,href){const a=document.createElement('a');a.download=name;a.href=href;a.click()}
function snapshot(){return{base:{...base},s:{...s},groupEnabled:{...groupEnabled},prompt:promptEl.value,seed:seedEl.value,fxSeed:fxSeed.value}}
function pushUndo(){undoStack.push(snapshot());if(undoStack.length>40)undoStack.shift()}
function restoreSnapshot(x){if(!x)return;stopAllSweeps();base={...defaults,...x.base};s={...defaults,...x.s};groupEnabled={...groupEnabled,...x.groupEnabled};if(x.prompt!=null)promptEl.value=x.prompt;if(x.seed!=null)seedEl.value=x.seed;if(x.fxSeed!=null)fxSeed.value=x.fxSeed;sync(true);renderStaticIfNeeded()}

function initState(resetGroups=false){s={...defaults};base={...defaults};for(const k in ranges){rate[k]=0;lfo[k]={mode:'off',amt:0,hz:1};if(!sweep[k])sweep[k]={timer:null,dir:0}}if(resetGroups||!Object.keys(groupEnabled).length)for(const [name,keys] of groups){groupEnabled[name]=true;for(const k of keys)keyGroup[k]=name}}
function build(){controls.innerHTML='';for(const [name,keys] of groups){const g=document.createElement('section');g.className='group';g.dataset.group=name;g.innerHTML=`<div class="groupHead"><h2>${name}</h2><button type="button" data-bypass="${name}">Bypass</button></div>`;keys.forEach(k=>g.appendChild(control(k)));controls.appendChild(g)}sync(true)}
function control(k){if(typeof defaults[k]==='boolean'){const l=document.createElement('label');l.className='check';l.innerHTML=`<input type="checkbox" data-bool="${k}"> ${label(k)}`;return l}const[min,max,step]=ranges[k],d=document.createElement('div');d.className='ctrl';d.innerHTML=`<label>${label(k)}</label><span class="val" id="v-${k}">0</span><input type="range" min="${min}" max="${max}" step="${step}" data-k="${k}"><div class="mini"><input title="change per second" type="number" step=".01" value="0" data-rate="${k}"><select title="LFO" data-mode="${k}"><option>off</option><option>sine</option><option>tri</option><option>square</option><option>noise</option><option>beat</option></select><input title="LFO amount" type="number" step=".01" value="0" data-amt="${k}"></div><div class="sweep"><button type="button" data-sweep="${k}" data-dir="1">L→R</button><button type="button" data-sweep="${k}" data-dir="-1">R→L</button><input title="jump size" type="number" step="${step}" value="${step}" data-jump="${k}"><input title="change interval ms" type="number" min="16" step="10" value="120" data-ms="${k}"></div>`;return d}
controls.addEventListener('pointerdown',e=>{if(e.target.dataset.k||e.target.dataset.bool)pushUndo()},{capture:true});
controls.addEventListener('input',e=>{const k=e.target.dataset.k,b=e.target.dataset.bool;if(k)setParam(k,+e.target.value,true);if(b){base[b]=s[b]=e.target.checked}if(e.target.dataset.rate)rate[e.target.dataset.rate]=+e.target.value||0;if(e.target.dataset.mode)lfo[e.target.dataset.mode].mode=e.target.value;if(e.target.dataset.amt)lfo[e.target.dataset.amt].amt=+e.target.value||0;sync(false);renderStaticIfNeeded()});
controls.addEventListener('click',e=>{if(e.target.dataset.sweep)toggleSweep(e.target.dataset.sweep,+e.target.dataset.dir);if(e.target.dataset.bypass)toggleGroup(e.target.dataset.bypass)});
function toggleGroup(name,forced){groupEnabled[name]=forced==null?!groupEnabled[name]:!!forced;sync(false);renderStaticIfNeeded()}
function setParam(k,value,setBase=false){if(ranges[k])value=clamp(value,ranges[k][0],ranges[k][1]);s[k]=value;if(setBase)base[k]=value}
function toggleSweep(k,dir){if(sweep[k]?.timer&&sweep[k].dir===dir){stopSweep(k);sync(false);return}stopSweep(k);const[min,max]=ranges[k];setParam(k,dir>0?min:max,true);const msInput=document.querySelector(`[data-ms="${k}"]`),jumpInput=document.querySelector(`[data-jump="${k}"]`);const tick=()=>{const ms=Math.max(16,+(msInput?.value||120)),jump=Math.max(paramStep(k),Math.abs(+(jumpInput?.value||paramStep(k))));let next=base[k]+dir*jump;if(next>max)next=min;if(next<min)next=max;setParam(k,next,true);sync(false);renderStaticIfNeeded();clearInterval(sweep[k].timer);sweep[k].timer=setInterval(tick,ms)};sweep[k]={timer:setInterval(tick,Math.max(16,+(msInput?.value||120))),dir};sync(false);renderStaticIfNeeded()}
function stopSweep(k){if(sweep[k]?.timer)clearInterval(sweep[k].timer);sweep[k]={timer:null,dir:0}}
function stopAllSweeps(){for(const k in sweep)stopSweep(k)}
function sync(input){document.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;if(input||document.activeElement!==el)el.value=s[k];const v=$('v-'+k);if(v)v.textContent=(+s[k]).toFixed((el.step||'1').includes('.')?1:0)});document.querySelectorAll('[data-bool]').forEach(el=>{if(input)el.checked=!!s[el.dataset.bool]});document.querySelectorAll('[data-sweep]').forEach(btn=>{const k=btn.dataset.sweep,dir=+btn.dataset.dir;btn.classList.toggle('active',!!sweep[k]?.timer&&sweep[k].dir===dir)});document.querySelectorAll('.group').forEach(g=>{const on=groupEnabled[g.dataset.group]!==false;g.classList.toggle('bypassed',!on);const b=g.querySelector('[data-bypass]');if(b)b.textContent=on?'Bypass':'Enable'});seedRead.textContent=`seed ${seedEl.value}`;fpsRead.textContent=`${drawFps} fps`;recordRead.textContent=recorder&&recorder.state==='recording'?'recording':'idle';readout.textContent=`${media} ${ready?'ready':'empty'} · ${canvas.width}×${canvas.height} · ${playing?'animated':'still'} · ${Object.values(groupEnabled).filter(Boolean).length}/${groups.length} racks`}
function effectiveState(live){const out={...live};for(const[k,name]of Object.entries(keyGroup))if(groupEnabled[name]===false)out[k]=defaults[k];return out}

function load(f){pushUndo();const url=URL.createObjectURL(f);ready=false;placeholder.style.display='none';video.pause();video.removeAttribute('src');img.removeAttribute('src');frame=0;if(f.type.startsWith('image/')){inputMedia='image';media='image';playing=false;img.onload=()=>{ready=true;resize();drawOnce();loopStart()};img.src=url}else if(f.type.startsWith('video/')){inputMedia='video';media='video';playing=true;video.src=url;video.onloadedmetadata=()=>{ready=true;resize();video.play().catch(()=>{});loopStart()}}sync(false)}
file.onchange=e=>e.target.files[0]&&load(e.target.files[0]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');e.dataTransfer.files[0]&&load(e.dataTransfer.files[0])});
function refSize(){return inputMedia==='video'?[video.videoWidth,video.videoHeight]:inputMedia==='image'?[img.naturalWidth,img.naturalHeight]:[0,0]}
function refSource(){return inputMedia==='video'?video:img}
function size(){if(media==='generated'||media==='baked')return[sourceCanvas.width,sourceCanvas.height];if(media==='video')return[video.videoWidth,video.videoHeight];if(media==='image')return[img.naturalWidth,img.naturalHeight];return[0,0]}
function src(){if(media==='generated'||media==='baked')return sourceCanvas;return media==='video'?video:img}
function resize(){let[w,h]=size();if(!w)return;const q=clamp(+(quality?.value||.75),.2,1),sc=clamp(s.scale,.12,1)*q;w=Math.max(16,Math.floor(w*sc));h=Math.max(16,Math.floor(h*sc));if(canvas.width!==w||canvas.height!==h)for(const c of[canvas,tmp,fx,echo]){c.width=w;c.height=h}}
function loopStart(){if(!started){started=true;last=performance.now();requestAnimationFrame(loop)}}
function renderStaticIfNeeded(){if(ready&&!playing)drawOnce()}
function loop(t){requestAnimationFrame(loop);if(!ready)return;const dt=Math.min(.1,(t-last)/1000||0);last=t;if(playing)mods(t/1000,dt);if(media==='video'&&video.paused&&!playing)return;if(!playing&&media!=='video')return;if(t-lastDraw<1000/s.fps)return;lastDraw=t;draw(t)}
function drawOnce(){mods(performance.now()/1000,0);draw(performance.now())}
function mods(time,dt){const masterSpeed=+(master?.value||1),ma=+(macroA?.value||0),mb=+(macroB?.value||0),beat=+(bpm?.value||120)/60;for(const k in ranges){const[min,max]=ranges[k];base[k]=clamp(base[k]+(rate[k]||0)*dt*masterSpeed,min,max);const m=lfo[k]||{mode:'off',amt:0,hz:1};let x=0,p=time*(m.mode==='beat'?beat:m.hz||1)*masterSpeed;if(m.mode==='sine')x=Math.sin(p*Math.PI*2);else if(m.mode==='tri')x=2*Math.abs(2*(p-Math.floor(p+.5)))-1;else if(m.mode==='square'||m.mode==='beat')x=Math.sin(p*Math.PI*2)>0?1:-1;else if(m.mode==='noise')x=mulberry32(hash32(`${fxSeed.value}|${k}|${Math.floor(time*10)}`))()*2-1;s[k]=clamp(base[k]+x*m.amt+(ma-mb)*m.amt*.2,min,max)}}
function updateFps(t){fpsFrames++;if(t-fpsWindow>=500){drawFps=Math.round(fpsFrames*1000/(t-fpsWindow));fpsFrames=0;fpsWindow=t}}
function draw(t){if(media==='generated')generateSource(t/1000);resize();frame++;updateFps(t);fxRandom=mulberry32(hash32(`${fxSeed.value}|${frame}`));const w=canvas.width,h=canvas.height;if(!w||!h)return;tctx.clearRect(0,0,w,h);tctx.save();tctx.translate(w/2,h/2);tctx.drawImage(src(),-w/2,-h/2,w,h);tctx.restore();const live=s;s=effectiveState(live);ctx.clearRect(0,0,w,h);if(s.echo){ctx.globalAlpha=s.echo/100;ctx.drawImage(echo,0,0);ctx.globalAlpha=1}if(s.feedbackZoom)feedback(w,h);if(s.mirror){ctx.save();ctx.translate(w,0);ctx.scale(-1,1);ctx.drawImage(tmp,0,0);ctx.restore()}else if(s.kaleido>1)kaleido(w,h);else if(s.tiles>1)tiles(w,h);else wobble(w,h,t);if(s.ripples)ripple(w,h,t);if(s.displace)displace(w,h,t);if(s.rgb||s.chromaNoise)rgbShift(t);pixels(w,h);if(s.glow)glow(w,h);if(s.edge)edge(w,h);if(s.emboss)emboss(w,h);if(s.half)half(w,h);if(s.ascii)asciiFx(w,h);if(s.pixel>1)pixelFx(w,h);if(s.sort)sortPix(w,h);if(s.blocks)blocksFx(w,h);if(s.blockInvert)invertBlocks(w,h);if(s.datamosh)datamosh(w,h);if(s.melt)melt(w,h);if(s.shred)shred(w,h);if(s.lineOffset)lineOffset(w,h,t);if(s.tunnel)tunnel(w,h);if(s.prism)prism(w,h,t);if(s.ghost)ghost(w,h,t);if(s.scan)scan(w,h,t);if(s.scratch)scratches(w,h);if(s.bands)bands(w,h,t);if(s.strobe&&Math.sin(t/1000*s.strobeRate*Math.PI*2)>0)flash(w,h);if(s.vignette)vignette(w,h);ectx.clearRect(0,0,w,h);ectx.drawImage(canvas,0,0);s=live;sync(false)}

function generatorConfig(){return{mode:genMode.value,engine:genEngine.value,motion:genMotion.value,seed:seedEl.value,prompt:promptEl.value.toLowerCase(),w:clamp(+genW.value||512,64,1024),h:clamp(+genH.value||512,64,1024),cell:clamp(+cellSize.value||8,2,32),speed:clamp(+genSpeed.value||1,0,4)}}
function paletteFor(c){const h=hash32(`${c.seed}|${c.prompt}`)%360;let hues=[h,(h+42)%360,(h+178)%360,(h+300)%360];if(c.prompt.includes('warm'))hues=[10,28,48,340];if(c.prompt.includes('forest'))hues=[92,126,42,178];if(c.prompt.includes('water'))hues=[185,205,225,170];if(c.prompt.includes('space'))hues=[255,285,210,325];if(c.prompt.includes('monochrome'))hues=[h,h,h,h];if(c.prompt.includes('neon'))return hues.map((x,i)=>`hsl(${x} 100% ${i?58:38}%)`);return hues.map((x,i)=>`hsl(${x} ${c.prompt.includes('monochrome')?8:72}% ${34+i*11}%)`)}
function motionTime(c,time){if(c.motion==='static')return 0;const t=time*c.speed;if(c.motion==='pulse')return Math.sin(t*2)*1.2;if(c.motion==='orbit')return t*1.8;if(c.motion==='wave')return t*2.6;return t}
function generateSource(time=0){const c=generatorConfig();if(sourceCanvas.width!==c.w||sourceCanvas.height!==c.h){sourceCanvas.width=c.w;sourceCanvas.height=c.h}sourceCtx.imageSmoothingEnabled=false;if(c.engine==='reference'&&inputMedia!=='none'&&refSize()[0])drawReferenceGenerator(c,time);else if(c.engine==='cellular')drawCellular(c,time);else drawMath(c,time)}
function drawMath(c,time){const pal=paletteFor(c),tt=motionTime(c,time),cs=c.cell,w=c.w,h=c.h,chars=' .:-=+*#%@';sourceCtx.fillStyle='#05060b';sourceCtx.fillRect(0,0,w,h);const sym=c.prompt.includes('symmetry')||c.prompt.includes('mirror'),rings=c.prompt.includes('ring')||c.prompt.includes('orb'),grid=c.prompt.includes('grid')||c.prompt.includes('circuit'),city=c.prompt.includes('city'),space=c.prompt.includes('space'),organic=c.prompt.includes('organic')||c.prompt.includes('forest');sourceCtx.font=`${Math.max(6,cs)}px ui-monospace,monospace`;sourceCtx.textBaseline='top';for(let y=0;y<h;y+=cs)for(let x=0;x<w;x+=cs){let u=(x-w/2)/Math.min(w,h),v=(y-h/2)/Math.min(w,h);if(sym)u=Math.abs(u);let q=Math.sin((u*11+tt)*2.2)+Math.cos((v*9-tt*.7)*2.4)+Math.sin((u+v)*17+tt*.9);if(rings)q+=Math.sin(Math.hypot(u,v)*42-tt*3)*1.4;if(grid)q+=Math.sin(u*70)*.35+Math.sin(v*70)*.35;if(organic)q+=Math.sin(u*9+Math.cos(v*8+tt))*1.1;if(city){const skyline=.18+coordNoise(Math.floor(x/cs),0,2)*.42;q+=y/h>1-skyline?2.5:-.8}if(space&&coordNoise(Math.floor(x/cs),Math.floor(y/cs),7)>.965)q+=4;const jitter=(coordNoise(Math.floor(x/cs),Math.floor(y/cs),Math.floor(tt*3))-0.5)*1.4;let n=clamp((q+jitter+3.6)/7.2,0,1),idx=Math.min(pal.length-1,Math.floor(n*pal.length));if(c.mode==='ascii'){sourceCtx.fillStyle=pal[idx];sourceCtx.fillText(chars[Math.min(chars.length-1,Math.floor(n*chars.length))],x,y)}else{sourceCtx.fillStyle=pal[idx];sourceCtx.fillRect(x,y,cs,cs);if(c.mode==='hybrid'&&n>.62){sourceCtx.fillStyle=n>.82?'#fff9':'#0009';sourceCtx.fillText(chars[Math.min(chars.length-1,Math.floor(n*chars.length))],x,y)}}}}
function drawCellular(c,time){const pal=paletteFor(c),cs=c.cell,w=c.w,h=c.h,chars=' ·:+#@',step=Math.floor(motionTime(c,time)*5),gx=Math.ceil(w/cs),gy=Math.ceil(h/cs);sourceCtx.fillStyle='#03050a';sourceCtx.fillRect(0,0,w,h);sourceCtx.font=`${Math.max(6,cs)}px ui-monospace,monospace`;sourceCtx.textBaseline='top';for(let y=0;y<gy;y++)for(let x=0;x<gx;x++){let sum=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)sum+=coordNoise((x+xx+gx)%gx,(y+yy+gy)%gy,step);const alive=sum/9>.51+(Math.sin(step*.3+x*.13-y*.09)*.035),n=alive?clamp((sum/9-.45)*3,0,1):coordNoise(x,y,step+99)*.16,idx=Math.min(pal.length-1,Math.floor(n*pal.length));sourceCtx.fillStyle=alive?pal[idx]:'#05070b';if(c.mode==='ascii')sourceCtx.fillText(chars[Math.min(chars.length-1,Math.floor(n*chars.length))],x*cs,y*cs);else{sourceCtx.fillRect(x*cs,y*cs,cs,cs);if(c.mode==='hybrid'&&alive){sourceCtx.fillStyle='#fff8';sourceCtx.fillText(chars[4],x*cs,y*cs)}}}}
function drawReferenceGenerator(c,time){const[w,h]=refSize(),srcRef=refSource();sourceCtx.fillStyle='#000';sourceCtx.fillRect(0,0,c.w,c.h);sourceCtx.drawImage(srcRef,0,0,w,h,0,0,c.w,c.h);const cs=c.cell,small=document.createElement('canvas'),sc=small.getContext('2d',{willReadFrequently:true}),sw=Math.max(1,Math.ceil(c.w/cs)),sh=Math.max(1,Math.ceil(c.h/cs));small.width=sw;small.height=sh;sc.drawImage(sourceCanvas,0,0,sw,sh);const im=sc.getImageData(0,0,sw,sh),d=im.data,chars=' .:-=+*#%@';sourceCtx.fillStyle='#000';sourceCtx.fillRect(0,0,c.w,c.h);sourceCtx.font=`${Math.max(6,cs)}px ui-monospace,monospace`;sourceCtx.textBaseline='top';for(let y=0;y<sh;y++)for(let x=0;x<sw;x++){const i=(y*sw+x)*4,br=(d[i]+d[i+1]+d[i+2])/765,shift=Math.sin(motionTime(c,time)+y*.12)*cs*.35,px=x*cs+shift,py=y*cs;if(c.mode==='ascii'){sourceCtx.fillStyle=`rgb(${d[i]},${d[i+1]},${d[i+2]})`;sourceCtx.fillText(chars[Math.floor(br*(chars.length-1))],px,py)}else{sourceCtx.fillStyle=`rgb(${d[i]},${d[i+1]},${d[i+2]})`;sourceCtx.fillRect(px,py,cs,cs);if(c.mode==='hybrid'&&br>.55){sourceCtx.fillStyle='#fff9';sourceCtx.fillText(chars[Math.floor(br*(chars.length-1))],px,py)}}}}
function startGenerated(){pushUndo();media='generated';ready=true;playing=genMotion.value!=='static';placeholder.style.display='none';generateSource(0);resize();drawOnce();loopStart();sync(false)}
function exportAscii(){if(!ready)return;const srcC=media==='generated'||media==='baked'?sourceCanvas:canvas,cols=80,ratio=srcC.height/srcC.width,rows=Math.max(8,Math.round(cols*ratio*.48)),c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=cols;c.height=rows;x.drawImage(srcC,0,0,cols,rows);const d=x.getImageData(0,0,cols,rows).data,chars=' .,:;irsXA253hMHGS#9B&@',lines=[];for(let y=0;y<rows;y++){let line='';for(let xx=0;xx<cols;xx++){const i=(y*cols+xx)*4,br=(d[i]+d[i+1]+d[i+2])/765;line+=chars[Math.floor(br*(chars.length-1))]}lines.push(line)}download('circuitbend-ascii.txt','data:text/plain;charset=utf-8,'+encodeURIComponent(lines.join('\n')))}
function bakeOutput(){if(!canvas.width)return;pushUndo();sourceCanvas.width=canvas.width;sourceCanvas.height=canvas.height;sourceCtx.drawImage(canvas,0,0);media='baked';ready=true;playing=false;inputMedia='none';echo.width=canvas.width;echo.height=canvas.height;ectx.clearRect(0,0,echo.width,echo.height);drawOnce();sync(false)}

function wobble(w,h,t){if(!s.wobble){ctx.drawImage(tmp,0,0);return}for(let y=0;y<h;y+=2){const dx=Math.sin(y/h*s.wobbleFreq*Math.PI*2+t/1000*s.wave)*s.wobble;ctx.drawImage(tmp,0,y,w,2,dx,y,w,2)}}
function ripple(w,h,t){fctx.clearRect(0,0,w,h);fctx.drawImage(canvas,0,0);for(let y=0;y<h;y+=2){const dx=Math.sin((y+t*.03)/h*s.rippleFreq*Math.PI*2)*s.ripples*.45;ctx.drawImage(fx,0,y,w,2,dx,y,w,2)}}
function displace(w,h,t){fctx.clearRect(0,0,w,h);fctx.drawImage(canvas,0,0);const band=Math.max(2,Math.floor(4+s.displace/8));for(let y=0;y<h;y+=band){const dx=(Math.sin(y*.071+t*.0017)+Math.sin(y*.017-t*.0023))*s.displace*.5;ctx.drawImage(fx,0,y,w,band,dx,y,w,band)}}
function kaleido(w,h){const n=Math.max(1,Math.floor(s.kaleido));ctx.save();ctx.translate(w/2,h/2);for(let i=0;i<n;i++){ctx.save();ctx.rotate(i*Math.PI*2/n);if(i%2)ctx.scale(-1,1);ctx.drawImage(tmp,-w/2,-h/2,w,h);ctx.restore()}ctx.restore()}
function tiles(w,h){const n=Math.max(2,Math.floor(s.tiles));for(let y=0;y<n;y++)for(let x=0;x<n;x++){ctx.save();ctx.translate(x*w/n,y*h/n);if((x+y)%2)ctx.scale(-1,1);ctx.drawImage(tmp,0,0,w,h,((x+y)%2?-w/n:0),0,w/n,h/n);ctx.restore()}}
function rgbShift(){const amp=s.rgb+s.chromaNoise*rnd()*.5,a=s.angle*Math.PI/180,dx=Math.cos(a)*amp,dy=Math.sin(a)*amp;ctx.globalCompositeOperation='screen';ctx.globalAlpha=.55;ctx.filter='sepia(1) saturate(8) hue-rotate(-45deg)';ctx.drawImage(canvas,dx,dy);ctx.filter='sepia(1) saturate(8) hue-rotate(75deg)';ctx.drawImage(canvas,-dx*.7,-dy*.7);ctx.filter='none';ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over'}
function pixels(w,h){const imgd=ctx.getImageData(0,0,w,h),d=imgd.data,c=(259*(s.contrast+255))/(255*(259-s.contrast)),lev=s.poster||Math.pow(2,Math.round(s.bits)),bayer=[0,8,2,10,12,4,14,6,3,11,1,9,15,7,13,5];for(let i=0;i<d.length;i+=4){let r=c*(d[i]-128)+128+s.bright,g=c*(d[i+1]-128)+128+s.bright,b=c*(d[i+2]-128)+128+s.bright,[hh,ss,ll]=rgbToHsl(r,g,b);hh=(hh+s.hue/360+1)%1;ss=clamp(ss*(1+s.sat/100),0,1);[r,g,b]=hslToRgb(hh,ss,ll);if(s.gray){let y=.299*r+.587*g+.114*b;r=g=b=y}if(s.invert){r=255-r;g=255-g;b=255-b}if(s.solar&&((r+g+b)/3)>s.solar){r=255-r;g=255-g;b=255-b}if(s.duotone){const y=(r+g+b)/765,amt=s.duotone/100;r=r*(1-amt)+(40+220*y)*amt;g=g*(1-amt)+(20+80*y)*amt;b=b*(1-amt)+(120+120*(1-y))*amt}if(s.posterBurn){const y=(r+g+b)/3;if(y<80*s.posterBurn/100){r*=1.4;g*=.35;b*=.18}}if(lev<256){r=Math.round(r/255*(lev-1))/(lev-1)*255;g=Math.round(g/255*(lev-1))/(lev-1)*255;b=Math.round(b/255*(lev-1))/(lev-1)*255}if(s.noise){const n=(rnd()*2-1)*s.noise;r+=n;g+=n;b+=n}if(s.dither){const p=i/4,x=p%w,y=Math.floor(p/w),th=(bayer[(y%4)*4+(x%4)]/15-.5)*s.dither*2;r+=th;g+=th;b+=th}if(s.threshold){const y=.299*r+.587*g+.114*b,v=y>=s.threshold?255:0;r=g=b=v}d[i]=byte(r);d[i+1]=byte(g);d[i+2]=byte(b)}ctx.putImageData(imgd,0,0)}
function edge(w,h){const im=ctx.getImageData(0,0,w,h),d=im.data,o=ctx.createImageData(w,h),od=o.data;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4,a=(d[i]+d[i+1]+d[i+2])/3,b=(d[i+4]+d[i+5]+d[i+6])/3,c=(d[i+w*4]+d[i+w*4+1]+d[i+w*4+2])/3,e=Math.min(255,Math.abs(a-b)+Math.abs(a-c))*s.edge/40;od[i]=e;od[i+1]=e*.4+80;od[i+2]=255;od[i+3]=e}ctx.globalCompositeOperation='screen';ctx.putImageData(o,0,0);ctx.globalCompositeOperation='source-over'}
function glow(w,h){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.glow/120;ctx.filter=`blur(${Math.max(1,s.glow/10)}px) saturate(1.8)`;ctx.drawImage(canvas,0,0);ctx.filter='none';ctx.restore()}
function emboss(w,h){fctx.clearRect(0,0,w,h);fctx.drawImage(canvas,0,0);ctx.save();ctx.globalAlpha=s.emboss/100;ctx.globalCompositeOperation='overlay';ctx.filter='grayscale(1) contrast(2)';ctx.drawImage(fx,-2,-2);ctx.globalCompositeOperation='difference';ctx.drawImage(fx,2,2);ctx.filter='none';ctx.restore()}
function half(w,h){const st=Math.max(3,Math.floor(s.half));ctx.save();ctx.globalCompositeOperation='multiply';for(let y=0;y<h;y+=st)for(let x=0;x<w;x+=st){const p=ctx.getImageData(x,y,1,1).data,br=(p[0]+p[1]+p[2])/765;ctx.beginPath();ctx.fillStyle='#000';ctx.arc(x,y,(1-br)*st*.55,0,Math.PI*2);ctx.fill()}ctx.restore()}
function asciiFx(w,h){const st=Math.max(4,Math.floor(s.ascii)),im=ctx.getImageData(0,0,w,h),d=im.data,ch=' .:-=+*#%@';ctx.fillStyle='#05050a';ctx.fillRect(0,0,w,h);ctx.font=st+'px monospace';ctx.fillStyle='#dffcff';for(let y=0;y<h;y+=st)for(let x=0;x<w;x+=st){const i=(y*w+x)*4,br=(d[i]+d[i+1]+d[i+2])/765;ctx.fillText(ch[Math.floor(br*(ch.length-1))],x,y+st)}}
function pixelFx(w,h){const p=Math.max(1,s.pixel),sw=Math.max(1,Math.floor(w/p)),sh=Math.max(1,Math.floor(h/p));tctx.clearRect(0,0,w,h);tctx.imageSmoothingEnabled=false;tctx.drawImage(canvas,0,0,sw,sh);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,sw,sh,0,0,w,h);ctx.imageSmoothingEnabled=true}
function sortPix(w,h){const im=ctx.getImageData(0,0,w,h),d=im.data,rows=Math.floor(h*s.sort/100);for(let n=0;n<rows;n++){const y=Math.floor(rnd()*h),row=[];for(let x=0;x<w;x++){const i=(y*w+x)*4,br=(d[i]+d[i+1]+d[i+2])/3;if(br>110)row.push([br,d[i],d[i+1],d[i+2],x])}row.sort((a,b)=>a[0]-b[0]);row.forEach((p,j)=>{const i=(y*w+p[4])*4;d[i]=row[j][1];d[i+1]=row[j][2];d[i+2]=row[j][3]})}ctx.putImageData(im,0,0)}
function blocksFx(w,h){for(let i=0;i<s.blocks;i++){const bw=4+rnd()*s.blockSize,bh=4+rnd()*s.blockSize,x=rnd()*w,y=rnd()*h;ctx.drawImage(canvas,x,y,bw,bh,x+(rnd()*2-1)*s.blockDrift,y,bw,bh)}}
function invertBlocks(w,h){for(let i=0;i<s.blockInvert/2;i++){const bw=10+rnd()*90,bh=10+rnd()*90,x=rnd()*Math.max(1,w-bw),y=rnd()*Math.max(1,h-bh);fx.width=Math.max(1,Math.floor(bw));fx.height=Math.max(1,Math.floor(bh));fctx.filter='invert(1) hue-rotate(90deg)';fctx.drawImage(canvas,x,y,bw,bh,0,0,bw,bh);fctx.filter='none';ctx.drawImage(fx,x,y)}fx.width=w;fx.height=h}
function datamosh(w,h){ctx.save();ctx.globalAlpha=s.datamosh/130;const count=Math.floor(s.datamosh/4);for(let i=0;i<count;i++){const bh=2+rnd()*Math.max(4,h*.08),y=rnd()*Math.max(1,h-bh),shift=(rnd()*2-1)*(20+s.datamosh*1.8),source=rnd()>.45?echo:canvas;ctx.drawImage(source,0,y,w,bh,shift,y,w,bh)}ctx.restore()}
function melt(w,h){for(let x=0;x<w;x+=4)if(rnd()<s.melt/100)ctx.drawImage(canvas,x,0,3,h,x,rnd()*20,3,h)}
function shred(w,h){for(let y=0;y<h;y+=8)if(rnd()<s.shred/100)ctx.drawImage(canvas,0,y,w,6,(rnd()*2-1)*80,y,w,6)}
function lineOffset(w,h,t){for(let y=0;y<h;y+=5)if(rnd()<.25)ctx.drawImage(canvas,0,y,w,3,Math.sin(y*.07+t*.002)*s.lineOffset,y,w,3)}
function feedback(w,h){const z=s.feedbackZoom/100,sw=w*(1-z),sh=h*(1-z);ctx.save();ctx.globalAlpha=.68;ctx.globalCompositeOperation='screen';ctx.drawImage(echo,(w-sw)/2,(h-sh)/2,sw,sh);ctx.restore()}
function tunnel(w,h){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.tunnel/180;for(let i=1;i<8;i++){const sc=1-i*.045*s.tunnel/100;ctx.drawImage(canvas,w*(1-sc)/2,h*(1-sc)/2,w*sc,h*sc)}ctx.restore()}
function prism(w,h,t){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.prism/160;for(let i=0;i<3;i++){ctx.save();ctx.translate(w/2,h/2);ctx.rotate((i-1)*s.prism*.002*Math.sin(t*.001));ctx.drawImage(canvas,-w/2+(i-1)*s.prism*.25,-h/2,w,h);ctx.restore()}ctx.restore()}
function ghost(w,h,t){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.ghost/140;ctx.drawImage(canvas,Math.sin(t*.002)*s.ghost*.7,Math.cos(t*.0015)*s.ghost*.35);ctx.restore()}
function scan(w,h,t){ctx.save();ctx.globalAlpha=s.scan/100;ctx.fillStyle='#000';for(let y=(t/80)%4;y<h;y+=4)ctx.fillRect(0,y,w,1);ctx.restore()}
function scratches(w,h){ctx.save();ctx.globalAlpha=s.scratch/140;ctx.strokeStyle='#fff';for(let i=0;i<s.scratch/2;i++){const x=rnd()*w;ctx.beginPath();ctx.moveTo(x,rnd()*h);ctx.lineTo(x+rnd()*30-15,rnd()*h);ctx.stroke()}ctx.restore()}
function bands(w,h,t){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=s.bands/100;for(let y=0;y<h;y+=18){ctx.fillStyle=`hsl(${(y+t*.02*s.bandSpeed)%360},100%,55%)`;ctx.fillRect(0,y,w,8)}ctx.restore()}
function flash(w,h){ctx.save();ctx.globalAlpha=s.strobe/100;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.restore()}
function vignette(w,h){const g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.1,w/2,h/2,Math.max(w,h)*.7);g.addColorStop(0,'#0000');g.addColorStop(1,`rgba(0,0,0,${s.vignette/100})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h,ss,l=(max+min)/2;if(max===min)h=ss=0;else{const d=max-min;ss=l>.5?d/(2-max-min):d/(max+min);h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;h/=6}return[h,ss,l]}
function hslToRgb(h,ss,l){let r,g,b;if(ss===0)r=g=b=l;else{const f=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p},q=l<.5?l*(1+ss):l+ss-l*ss,p=2*l-q;r=f(p,q,h+1/3);g=f(p,q,h);b=f(p,q,h-1/3)}return[r*255,g*255,b*255]}

function applyPreset(name){pushUndo();stopAllSweeps();initState(false);Object.assign(base,presets[name]||{});Object.assign(s,base);sync(true);renderStaticIfNeeded()}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
$('generateBtn').onclick=startGenerated;$('variationBtn').onclick=()=>{seedEl.value=`${seedEl.value.replace(/-v\d+$/,'')}-v${1+(hash32(seedEl.value+Date.now())%999)}`;startGenerated()};$('asciiBtn').onclick=exportAscii;$('useOutputBtn').onclick=bakeOutput;
$('playBtn').onclick=()=>{if(!ready)return;if(media==='video'){if(video.paused){video.play().catch(()=>{});playing=true}else{video.pause();playing=false}}else playing=!playing;loopStart();sync(false);renderStaticIfNeeded()};
$('stillBtn').onclick=()=>{playing=false;if(media==='video')video.pause();renderStaticIfNeeded();sync(false)};
$('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('app').requestFullscreen();$('reflowBtn').onclick=()=>window.dispatchEvent(new Event('resize'));
$('undoBtn').onclick=()=>restoreSnapshot(undoStack.pop());$('resetBtn').onclick=()=>{pushUndo();stopAllSweeps();initState(false);sync(true);renderStaticIfNeeded()};
$('randomBtn').onclick=()=>rand(.35);$('chaosBtn').onclick=()=>rand(1);$('disableAllBtn').onclick=()=>{pushUndo();for(const name in groupEnabled)groupEnabled[name]=false;sync(false);renderStaticIfNeeded()};$('enableAllBtn').onclick=()=>{pushUndo();for(const name in groupEnabled)groupEnabled[name]=true;sync(false);renderStaticIfNeeded()};
$('snapBtn').onclick=()=>{if(!ready)return;if(!playing)drawOnce();download(media==='video'?'circuitbend-video-frame.png':'circuitbend-art.png',canvas.toDataURL('image/png'))};
function rand(p){pushUndo();const r=mulberry32(hash32(`${fxSeed.value}|${Date.now()}|${p}`));for(const k in ranges){const[min,max]=ranges[k];setParam(k,+(min+r()*(max-min)*p).toFixed(2),true)}for(const k in defaults)if(typeof defaults[k]==='boolean')base[k]=s[k]=r()<.18*p;sync(true);renderStaticIfNeeded()}
$('savePresetBtn').onclick=()=>{localStorage.setItem('circuitbend.snapshot',JSON.stringify(snapshot()));$('savePresetBtn').textContent='Saved';setTimeout(()=>$('savePresetBtn').textContent='Save snapshot',900)};
$('loadPresetBtn').onclick=()=>{try{const x=JSON.parse(localStorage.getItem('circuitbend.snapshot')||'null');if(x){pushUndo();restoreSnapshot(x)}}catch(e){console.warn(e)}};
quality.onchange=renderStaticIfNeeded;seedEl.onchange=()=>{if(media==='generated')startGenerated()};[genMode,genEngine,genMotion,genW,genH,cellSize,genSpeed].forEach(el=>el.onchange=()=>{if(media==='generated')startGenerated()});
function toggleRecording(){if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!canvas.captureStream||!window.MediaRecorder){alert('Canvas recording is not supported by this browser.');return}if(!ready){alert('Generate or load media first.');return}const stream=canvas.captureStream(Math.min(60,Math.max(1,s.fps))),types=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'],mimeType=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'';recordChunks=[];recorder=new MediaRecorder(stream,mimeType?{mimeType,videoBitsPerSecond:8000000}:{videoBitsPerSecond:8000000});recorder.ondataavailable=e=>{if(e.data?.size)recordChunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(recordChunks,{type:recorder.mimeType||'video/webm'}),url=URL.createObjectURL(blob);download('circuitbend-recording.webm',url);setTimeout(()=>URL.revokeObjectURL(url),30000);$('recordBtn').classList.remove('recording');$('recordBtn').textContent='Record WebM';sync(false)};recorder.start(500);$('recordBtn').classList.add('recording');$('recordBtn').textContent='Stop recording';if(!playing){playing=true;loopStart()}sync(false)}
$('recordBtn').onclick=toggleRecording;
window.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();restoreSnapshot(undoStack.pop())}else if(e.code==='Space'){e.preventDefault();$('playBtn').click()}else if(e.key.toLowerCase()==='g')startGenerated();else if(e.key.toLowerCase()==='r')rand(.35);else if(e.key.toLowerCase()==='s')$('snapBtn').click()});
window.addEventListener('beforeunload',()=>{stopAllSweeps();if(recorder?.state==='recording')recorder.stop()});

initState(true);build();sync(true);
