const $=id=>document.getElementById(id);
const video=$('video'),img=$('image'),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const file=$('file'),drop=$('drop'),readout=$('readout'),controls=$('controls'),placeholder=$('placeholder');
const defaults={scale:.72,fps:45,bright:0,contrast:0,sat:0,hue:0,invert:false,gray:false,rgb:0,angle:0,poster:0,bits:8,noise:0,pixel:1,sort:0,blocks:0,blockSize:40,blockDrift:80,scan:0,wobble:0,wobbleFreq:8,wave:2,edge:0,half:0,ascii:0,solar:0,melt:0,shred:0,kaleido:0,tiles:0,vignette:0,mirror:false,strobe:0,strobeRate:8};
let s={...defaults},base={...defaults},rate={},lfo={},media='none',ready=false,playing=false,last=0,lastDraw=0,frame=0;
let tmp=document.createElement('canvas'),tctx=tmp.getContext('2d',{willReadFrequently:true});
let echo=document.createElement('canvas'),ectx=echo.getContext('2d',{willReadFrequently:true});
const groups=[['Render',['scale','fps']],['Color',['bright','contrast','sat','hue','invert','gray','solar']],['Glitch',['rgb','angle','poster','bits','noise','pixel','sort','blocks','blockSize','blockDrift']],['Geometry',['wobble','wobbleFreq','wave','mirror','kaleido','tiles','melt','shred']],['Print and neon',['edge','half','ascii','scan','vignette','strobe','strobeRate']]];
const ranges={scale:[.12,1,.01],fps:[1,60,1],bright:[-120,120,1],contrast:[-120,140,1],sat:[-100,360,1],hue:[-180,180,1],rgb:[0,120,1],angle:[0,360,1],poster:[0,16,1],bits:[1,8,1],noise:[0,180,1],pixel:[1,80,1],sort:[0,100,1],blocks:[0,140,1],blockSize:[4,260,1],blockDrift:[0,360,1],scan:[0,100,1],wobble:[0,120,1],wobbleFreq:[1,70,.1],wave:[-40,40,.1],edge:[0,100,1],half:[0,40,1],ascii:[0,32,1],solar:[0,255,1],melt:[0,100,1],shred:[0,100,1],kaleido:[0,12,1],tiles:[0,12,1],vignette:[0,100,1],strobe:[0,100,1],strobeRate:[1,60,.1]};
function label(k){return k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}
function build(){controls.innerHTML='';for(const [name,keys] of groups){let g=document.createElement('section');g.className='group';g.innerHTML='<h2>'+name+'</h2>';for(const k of keys)g.appendChild(control(k));controls.appendChild(g)}sync(true)}
function control(k){if(typeof defaults[k]==='boolean'){let l=document.createElement('label');l.className='check';l.innerHTML=`<input type="checkbox" data-bool="${k}"> ${label(k)}`;return l}let [min,max,step]=ranges[k],d=document.createElement('div');d.className='ctrl';rate[k]=0;lfo[k]={mode:'off',amt:0,hz:1};d.innerHTML=`<label>${label(k)}</label><span class="val" id="v-${k}">0</span><input type="range" min="${min}" max="${max}" step="${step}" data-k="${k}"><div class="mini"><input title="change per second" type="number" step=".01" value="0" data-rate="${k}"><select title="LFO" data-mode="${k}"><option>off</option><option>sine</option><option>tri</option><option>square</option><option>noise</option></select><input title="LFO amount" type="number" step=".01" value="0" data-amt="${k}"></div>`;return d}
controls.addEventListener('input',e=>{let k=e.target.dataset.k,b=e.target.dataset.bool;if(k){base[k]=s[k]=+e.target.value}if(b){base[b]=s[b]=e.target.checked}if(e.target.dataset.rate)rate[e.target.dataset.rate]=+e.target.value||0;if(e.target.dataset.mode)lfo[e.target.dataset.mode].mode=e.target.value;if(e.target.dataset.amt)lfo[e.target.dataset.amt].amt=+e.target.value||0;sync(false);if(media==='image'&&!playing)drawOnce()});
function sync(input){document.querySelectorAll('[data-k]').forEach(el=>{let k=el.dataset.k;if(input)el.value=base[k];let v=$('v-'+k);if(v)v.textContent=(+s[k]).toFixed((el.step||'1').includes('.')?1:0)});document.querySelectorAll('[data-bool]').forEach(el=>{if(input)el.checked=!!s[el.dataset.bool]});readout.textContent=`${media} ${ready?'ready':'empty'} ${canvas.width}x${canvas.height} ${media==='image'?'PNG still output':'video frame output'}`}
function load(f){let url=URL.createObjectURL(f);ready=false;placeholder.style.display='none';video.pause();video.removeAttribute('src');img.removeAttribute('src');if(f.type.startsWith('image/')){media='image';playing=false;img.onload=()=>{ready=true;resize();drawOnce();loopStart()};img.src=url}else if(f.type.startsWith('video/')){media='video';playing=true;video.src=url;video.onloadedmetadata=()=>{ready=true;resize();video.play();loopStart()}}sync(false)}
file.onchange=e=>e.target.files[0]&&load(e.target.files[0]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');e.dataTransfer.files[0]&&load(e.dataTransfer.files[0])});
function size(){return media==='video'?[video.videoWidth,video.videoHeight]:media==='image'?[img.naturalWidth,img.naturalHeight]:[0,0]}function src(){return media==='video'?video:img}
function resize(){let [w,h]=size();if(!w)return;w=Math.max(16,Math.floor(w*s.scale));h=Math.max(16,Math.floor(h*s.scale));if(canvas.width!==w||canvas.height!==h){for(const c of [canvas,tmp,echo]){c.width=w;c.height=h}}}
let started=false;function loopStart(){if(!started){started=true;last=performance.now();requestAnimationFrame(loop)}}
function loop(t){requestAnimationFrame(loop);if(!ready)return;let dt=Math.min(.1,(t-last)/1000||0);last=t;if(playing)mods(t/1000,dt);if(media==='image'&&!playing)return;if(media==='video'&&video.paused&&!playing)return;if(t-lastDraw<1000/s.fps)return;lastDraw=t;draw(t)}function drawOnce(){mods(performance.now()/1000,0);draw(performance.now())}
function mods(time,dt){for(const k in ranges){base[k]+=rate[k]*dt;let m=lfo[k],x=0,p=time*(m.hz||1);if(m.mode==='sine')x=Math.sin(p*Math.PI*2);else if(m.mode==='tri')x=2*Math.abs(2*(p-Math.floor(p+.5)))-1;else if(m.mode==='square')x=Math.sin(p*Math.PI*2)>0?1:-1;else if(m.mode==='noise')x=Math.random()*2-1;s[k]=base[k]+x*m.amt}}
function draw(t){resize();frame++;let w=canvas.width,h=canvas.height;tctx.clearRect(0,0,w,h);tctx.save();tctx.translate(w/2,h/2);if(s.mirror)tctx.scale(-1,1);tctx.drawImage(src(),-w/2,-h/2,w,h);tctx.restore();ctx.clearRect(0,0,w,h);if(s.kaleido>1)kaleido(w,h);else if(s.tiles>1)tiles(w,h);else wobble(w,h,t);if(s.rgb)rgb(t);pixels(w,h,t);if(s.edge)edge(w,h);if(s.half)half(w,h);if(s.ascii)ascii(w,h);if(s.pixel>1)pixel(w,h);if(s.sort)sortPix(w,h);if(s.blocks)blocks(w,h);if(s.melt)melt(w,h);if(s.shred)shred(w,h);if(s.scan)scan(w,h,t);if(s.strobe&&Math.sin(t/1000*s.strobeRate*Math.PI*2)>0)flash(w,h);if(s.vignette)vignette(w,h);sync(false)}
function wobble(w,h,t){if(!s.wobble){ctx.drawImage(tmp,0,0);return}for(let y=0;y<h;y+=2){let dx=Math.sin(y/h*s.wobbleFreq*Math.PI*2+t/1000*s.wave)*s.wobble;ctx.drawImage(tmp,0,y,w,2,dx,y,w,2)}}
function kaleido(w,h){let n=Math.max(1,Math.floor(s.kaleido));ctx.save();ctx.translate(w/2,h/2);for(let i=0;i<n;i++){ctx.save();ctx.rotate(i*Math.PI*2/n);if(i%2)ctx.scale(-1,1);ctx.drawImage(tmp,-w/2,-h/2,w,h);ctx.restore()}ctx.restore()}
function tiles(w,h){let n=Math.max(2,Math.floor(s.tiles));for(let y=0;y<n;y++)for(let x=0;x<n;x++){ctx.save();ctx.translate(x*w/n,y*h/n);if((x+y)%2)ctx.scale(-1,1);ctx.drawImage(tmp,0,0,w,h,((x+y)%2?-w/n:0),0,w/n,h/n);ctx.restore()}}
function rgb(t){let a=s.angle*Math.PI/180,dx=Math.cos(a)*s.rgb,dy=Math.sin(a)*s.rgb;ctx.globalCompositeOperation='screen';ctx.globalAlpha=.55;ctx.filter='sepia(1) saturate(8) hue-rotate(-45deg)';ctx.drawImage(canvas,dx,dy);ctx.filter='sepia(1) saturate(8) hue-rotate(75deg)';ctx.drawImage(canvas,-dx*.7,-dy*.7);ctx.filter='none';ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over'}
function pixels(w,h,t){let imgd=ctx.getImageData(0,0,w,h),d=imgd.data,c=(259*(s.contrast+255))/(255*(259-s.contrast)),lev=s.poster||Math.pow(2,Math.round(s.bits));for(let i=0;i<d.length;i+=4){let r=c*(d[i]-128)+128+s.bright,g=c*(d[i+1]-128)+128+s.bright,b=c*(d[i+2]-128)+128+s.bright,[hh,ss,ll]=rgbToHsl(r,g,b);hh=(hh+s.hue/360+1)%1;ss=Math.max(0,Math.min(1,ss*(1+s.sat/100)));[r,g,b]=hslToRgb(hh,ss,ll);if(s.gray){let y=.299*r+.587*g+.114*b;r=g=b=y}if(s.invert){r=255-r;g=255-g;b=255-b}if(s.solar&&((r+g+b)/3)>s.solar){r=255-r;g=255-g;b=255-b}if(lev<256){r=Math.round(r/255*(lev-1))/(lev-1)*255;g=Math.round(g/255*(lev-1))/(lev-1)*255;b=Math.round(b/255*(lev-1))/(lev-1)*255}if(s.noise){let n=(Math.random()*2-1)*s.noise;r+=n;g+=n;b+=n}d[i]=cl(r);d[i+1]=cl(g);d[i+2]=cl(b)}ctx.putImageData(imgd,0,0)}
function edge(w,h){let im=ctx.getImageData(0,0,w,h),d=im.data,o=ctx.createImageData(w,h),od=o.data;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=(y*w+x)*4,a=(d[i]+d[i+1]+d[i+2])/3,b=(d[i+4]+d[i+5]+d[i+6])/3,c=(d[i+w*4]+d[i+w*4+1]+d[i+w*4+2])/3,e=Math.min(255,Math.abs(a-b)+Math.abs(a-c))*s.edge/40;od[i]=e;od[i+1]=e*.4+80;od[i+2]=255;od[i+3]=e}ctx.globalCompositeOperation='screen';ctx.putImageData(o,0,0);ctx.globalCompositeOperation='source-over'}
function half(w,h){let st=Math.max(3,Math.floor(s.half));ctx.save();ctx.globalCompositeOperation='multiply';for(let y=0;y<h;y+=st)for(let x=0;x<w;x+=st){let p=ctx.getImageData(x,y,1,1).data,br=(p[0]+p[1]+p[2])/765;ctx.beginPath();ctx.fillStyle='#000';ctx.arc(x,y,(1-br)*st*.55,0,Math.PI*2);ctx.fill()}ctx.restore()}
function ascii(w,h){let st=Math.max(4,Math.floor(s.ascii)),im=ctx.getImageData(0,0,w,h),d=im.data,ch=' .:-=+*#%@';ctx.fillStyle='#05050a';ctx.fillRect(0,0,w,h);ctx.font=st+'px monospace';ctx.fillStyle='#dffcff';for(let y=0;y<h;y+=st)for(let x=0;x<w;x+=st){let i=(y*w+x)*4,br=(d[i]+d[i+1]+d[i+2])/765;ctx.fillText(ch[Math.floor(br*(ch.length-1))],x,y+st)}}
function pixel(w,h){let p=Math.max(1,s.pixel);tctx.imageSmoothingEnabled=false;tctx.drawImage(canvas,0,0,w/p,h/p);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,w/p,h/p,0,0,w,h);ctx.imageSmoothingEnabled=true}
function sortPix(w,h){let im=ctx.getImageData(0,0,w,h),d=im.data,rows=Math.floor(h*s.sort/100);for(let n=0;n<rows;n++){let y=Math.floor(Math.random()*h),row=[];for(let x=0;x<w;x++){let i=(y*w+x)*4,br=(d[i]+d[i+1]+d[i+2])/3;if(br>110)row.push([br,d[i],d[i+1],d[i+2],x])}row.sort((a,b)=>a[0]-b[0]);row.forEach((p,j)=>{let i=(y*w+p[4])*4;d[i]=row[j][1];d[i+1]=row[j][2];d[i+2]=row[j][3]})}ctx.putImageData(im,0,0)}
function blocks(w,h){for(let i=0;i<s.blocks;i++){let bw=4+Math.random()*s.blockSize,bh=4+Math.random()*s.blockSize,x=Math.random()*w,y=Math.random()*h;ctx.drawImage(canvas,x,y,bw,bh,x+(Math.random()*2-1)*s.blockDrift,y,bw,bh)}}
function melt(w,h){for(let x=0;x<w;x+=4)if(Math.random()<s.melt/100)ctx.drawImage(canvas,x,0,3,h,x,Math.random()*20,3,h)}function shred(w,h){for(let y=0;y<h;y+=8)if(Math.random()<s.shred/100)ctx.drawImage(canvas,0,y,w,6,(Math.random()*2-1)*80,y,w,6)}
function scan(w,h,t){ctx.save();ctx.globalAlpha=s.scan/100;ctx.fillStyle='#000';for(let y=(t/80)%4;y<h;y+=4)ctx.fillRect(0,y,w,1);ctx.restore()}function flash(w,h){ctx.save();ctx.globalAlpha=s.strobe/100;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.restore()}function vignette(w,h){let g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.1,w/2,h/2,Math.max(w,h)*.7);g.addColorStop(0,'#0000');g.addColorStop(1,`rgba(0,0,0,${s.vignette/100})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function cl(v){return Math.max(0,Math.min(255,v))}function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;let max=Math.max(r,g,b),min=Math.min(r,g,b),h,s,l=(max+min)/2;if(max===min)h=s=0;else{let d=max-min;s=l>.5?d/(2-max-min):d/(max+min);h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;h/=6}return[h,s,l]}function hslToRgb(h,s,l){let r,g,b;if(s===0)r=g=b=l;else{let f=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p},q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;r=f(p,q,h+1/3);g=f(p,q,h);b=f(p,q,h-1/3)}return[r*255,g*255,b*255]}
const presets={clean:{},xerox:{gray:true,contrast:80,poster:2,noise:20},neon:{edge:90,sat:180,rgb:18,scan:20},acid:{sat:260,hue:80,poster:6,kaleido:5,strobe:15},cctv:{gray:true,contrast:34,bright:-12,noise:38,scan:65,vignette:55},mosh:{poster:7,bits:5,rgb:18,blocks:22,sort:12,melt:20},ascii:{ascii:13,contrast:40,edge:20},thermal:{poster:8,sat:300,hue:-90,solar:120,noise:15},poster:{poster:5,half:14,contrast:25,sat:60},fracture:{shred:55,blocks:45,blockDrift:180,rgb:24,tiles:4},ritual:{kaleido:8,hue:120,edge:55,vignette:42},dirty:{contrast:18,sat:-18,rgb:9,noise:24,scan:55,wobble:7,vignette:38}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{initState();Object.assign(base,presets[b.dataset.preset]);Object.assign(s,base);sync(true);if(media==='image')drawOnce()});
function initState(){s={...defaults};base={...defaults};for(const k in ranges){rate[k]=0;if(lfo[k])lfo[k]={mode:'off',amt:0,hz:1}}}
$('playBtn').onclick=()=>{if(media==='video'){if(video.paused){video.play();playing=true}else{video.pause();playing=false}}else{playing=!playing}loopStart();sync(false);if(media==='image'&&!playing)drawOnce()};
$('stillBtn').onclick=()=>{playing=false;if(media==='video')video.pause();if(media==='image')drawOnce()};$('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('app').requestFullscreen();$('resetBtn').onclick=()=>{initState();sync(true);if(media==='image')drawOnce()};$('randomBtn').onclick=()=>rand(.35);$('chaosBtn').onclick=()=>rand(1);$('snapBtn').onclick=()=>{if(media==='image')drawOnce();let a=document.createElement('a');a.download=media==='image'?'circuitbend-picture.png':'circuitbend-video-frame.png';a.href=canvas.toDataURL('image/png');a.click()};function rand(p){for(const k in ranges){let [min,max]=ranges[k];base[k]=s[k]=+(min+Math.random()*(max-min)*p).toFixed(2)}for(const k in defaults)if(typeof defaults[k]==='boolean')base[k]=s[k]=Math.random()<.18*p;sync(true);if(media==='image')drawOnce()}
build();