(() => {
  const byId=id=>document.getElementById(id);
  const priorGenerateSource=generateSource;
  const STORAGE='circuitbend.webview.v1';
  const MAX_PIXEL_CELLS=180000;
  const MAX_GLYPH_CELLS=90000;
  const state={compact:true,tab:'all'};
  const art={pixelShape:'square',toneSteps:8,dither:'bayer4',gap:0,glyphSet:'dense',glyphChars:' .,:;irsXA253hMHGS#9B&@',glyphInvert:false,glyphColor:'source',glyphAspect:1,asciiBg:'#03050a'};
  const sample=document.createElement('canvas'),sctx=sample.getContext('2d',{willReadFrequently:true});
  let toastTimer=null;

  function addOption(select,value,label){if(select&&![...select.options].some(o=>o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=label;select.appendChild(o)}}
  [['maze','Maze / circuit'],['isometric','Isometric tiles'],['plasma','Plasma field'],['voronoi','Voronoi cells'],['interference','Wave interference']].forEach(([v,l])=>addOption(genEngine,v,l));
  [['ansi','ANSI color glyphs'],['braille','Braille texture']].forEach(([v,l])=>addOption(genMode,v,l));

  function el(tag,attrs={},html=''){const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else if(k==='text')n.textContent=v;else n.setAttribute(k,v)}if(html)n.innerHTML=html;return n}
  function injectUI(){
    const top=document.querySelector('.top');
    if(!top||byId('webviewBar'))return;
    const bar=el('div',{id:'webviewBar',class:'webviewBar'});
    bar.innerHTML='<button id="compactToggle" class="active" title="Keep the app inside a compact browser workspace">Compact</button><div class="webTabs"><button data-webtab="all" class="active">All</button><button data-webtab="source">Source</button><button data-webtab="art">Pixel / ASCII</button><button data-webtab="fx">FX</button><button data-webtab="output">Output</button></div><span id="webStatus" class="webStatus">ready</span>';
    top.after(bar);
    const actions=document.querySelector('.genActions');
    if(actions){
      const lab=el('details',{id:'artLab',class:'artLab webArt',open:''});
      lab.innerHTML=`<summary>Pixel / ASCII renderer</summary><div class="artLabGrid"><label>Pixel shape<select id="pixelShape"><option value="square">Square</option><option value="circle">Circle</option><option value="diamond">Diamond</option><option value="hline">Horizontal line</option><option value="vline">Vertical line</option><option value="cross">Cross</option></select></label><label>Tone steps<select id="toneSteps"><option>2</option><option>4</option><option selected>8</option><option>16</option><option>32</option></select></label><label>Dither<select id="artDither"><option value="none">None</option><option value="bayer2">Bayer 2×2</option><option value="bayer4" selected>Bayer 4×4</option><option value="noise">Seeded noise</option></select></label><label>Cell gap<input id="pixelGap" type="number" min="0" max="8" step="1" value="0"></label><label>Glyph set<select id="glyphSet"><option value="classic">Classic</option><option value="dense" selected>Dense</option><option value="blocks">Blocks</option><option value="binary">Binary</option><option value="technical">Technical</option><option value="braille">Braille</option><option value="custom">Custom</option></select></label><label id="glyphCharsWrap" class="glyphCustomHidden">Custom glyphs<input id="glyphChars" type="text" value=" .,:;irsXA253hMHGS#9B&@"></label><label>Glyph color<select id="glyphColor"><option value="source">Source color</option><option value="palette">Palette</option><option value="mono">Monochrome</option><option value="green">Terminal green</option><option value="amber">Terminal amber</option><option value="cyan">Terminal cyan</option></select></label><label>Glyph aspect<input id="glyphAspect" type="number" min=".5" max="2" step=".05" value="1"></label><label>ASCII background<input id="asciiBg" type="color" value="#03050a"></label><label class="inlineCheck">Invert glyphs<input id="glyphInvert" type="checkbox"></label></div><div class="artLabActions"><select id="structureQuick" title="Quickly switch to a generator designed for pixel/ASCII work"><option value="">Structure engine…</option><option value="maze">Maze / circuit</option><option value="isometric">Isometric tiles</option><option value="plasma">Plasma</option><option value="voronoi">Voronoi</option><option value="interference">Interference</option><option value="cellular">Cellular</option><option value="mandala">Mandala</option><option value="textsheet">Glyph sheet</option></select><button id="artResetBtn">Reset renderer</button><button id="artRandomBtn">Randomize renderer</button><span id="artReadout" class="artReadout">renderer ready</span></div>`;
      actions.before(lab);
    }
    const toast=el('div',{id:'webToast',class:'webToast'});document.body.appendChild(toast);
    markPanels();
  }

  function markPanels(){
    const generator=document.querySelector('.generator');if(!generator)return;
    const details=[...generator.querySelectorAll(':scope > details.advancedSection')];
    [promptEl,document.querySelector('.sourcePresetRow'),document.querySelector('.genGrid'),drop].filter(Boolean).forEach(x=>x.dataset.webpanel='source');
    if(details[0])details[0].dataset.webpanel='output';
    if(details[1])details[1].dataset.webpanel='art';
    const lab=byId('artLab');if(lab)lab.dataset.webpanel='art';
    const actions=document.querySelector('.genActions');if(actions)actions.dataset.webpanel='source art output';
  }

  function toast(msg){const n=byId('webToast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1800)}
  function saveLocal(){try{localStorage.setItem(STORAGE,JSON.stringify({state,art}))}catch{}}
  function loadLocal(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(x?.state)Object.assign(state,x.state);if(x?.art)Object.assign(art,x.art)}catch{}}
  function applyTab(tab){state.tab=['all','source','art','fx','output'].includes(tab)?tab:'all';document.body.dataset.webtab=state.tab;document.querySelectorAll('[data-webpanel]').forEach(n=>{const panels=(n.dataset.webpanel||'').split(/\s+/);n.classList.toggle('webHidden',state.tab!=='all'&&!panels.includes(state.tab))});const panel=document.querySelector('.panel');if(panel)panel.classList.toggle('webPanelHidden',!['all','fx'].includes(state.tab));document.querySelectorAll('[data-webtab]').forEach(b=>b.classList.toggle('active',b.dataset.webtab===state.tab));saveLocal()}
  function applyCompact(){document.body.classList.toggle('compactView',!!state.compact);const b=byId('compactToggle');if(b){b.classList.toggle('active',!!state.compact);b.textContent=state.compact?'Compact':'Comfort'}saveLocal()}

  const glyphSets={classic:' .:-=+*#%@',dense:' .,:;irsXA253hMHGS#9B&@',blocks:' ░▒▓█',binary:' 01',technical:' .+*xX#@',braille:' ⡀⡄⡆⣆⣧⣿'};
  function readArt(){art.pixelShape=byId('pixelShape')?.value||art.pixelShape;art.toneSteps=clamp(+(byId('toneSteps')?.value||art.toneSteps),2,32);art.dither=byId('artDither')?.value||art.dither;art.gap=clamp(+(byId('pixelGap')?.value||0),0,8);art.glyphSet=byId('glyphSet')?.value||art.glyphSet;art.glyphChars=byId('glyphChars')?.value||art.glyphChars;art.glyphInvert=!!byId('glyphInvert')?.checked;art.glyphColor=byId('glyphColor')?.value||art.glyphColor;art.glyphAspect=clamp(+(byId('glyphAspect')?.value||1),.5,2);art.asciiBg=byId('asciiBg')?.value||art.asciiBg;const wrap=byId('glyphCharsWrap');if(wrap)wrap.classList.toggle('glyphCustomHidden',art.glyphSet!=='custom');saveLocal()}
  function writeArt(){for(const [id,key] of [['pixelShape','pixelShape'],['toneSteps','toneSteps'],['artDither','dither'],['pixelGap','gap'],['glyphSet','glyphSet'],['glyphChars','glyphChars'],['glyphColor','glyphColor'],['glyphAspect','glyphAspect'],['asciiBg','asciiBg']]){const n=byId(id);if(n)n.value=String(art[key])}const inv=byId('glyphInvert');if(inv)inv.checked=!!art.glyphInvert;readArt()}
  function resetArt(){Object.assign(art,{pixelShape:'square',toneSteps:8,dither:'bayer4',gap:0,glyphSet:'dense',glyphChars:' .,:;irsXA253hMHGS#9B&@',glyphInvert:false,glyphColor:'source',glyphAspect:1,asciiBg:'#03050a'});writeArt();renderStaticIfNeeded();toast('Pixel / ASCII renderer reset')}
  function randomizeArt(){const r=mulberry32(hash32(`${seedEl.value}|renderer|${Date.now()}`)),shapes=['square','circle','diamond','hline','vline','cross'],dithers=['none','bayer2','bayer4','noise'],sets=['classic','dense','blocks','binary','technical','braille'],colors=['source','palette','mono','green','amber','cyan'],steps=[2,4,8,16];art.pixelShape=shapes[Math.floor(r()*shapes.length)];art.dither=dithers[Math.floor(r()*dithers.length)];art.glyphSet=sets[Math.floor(r()*sets.length)];art.glyphColor=colors[Math.floor(r()*colors.length)];art.toneSteps=steps[Math.floor(r()*steps.length)];art.gap=Math.floor(r()*3);art.glyphAspect=+(0.75+r()*.7).toFixed(2);art.glyphInvert=r()>.7;writeArt();renderStaticIfNeeded();toast('Renderer randomized')}

  function effectiveCell(c,mode){let cell=Math.max(2,+c.cell||8),aspect=mode==='pixel'?1:art.glyphAspect,limit=mode==='pixel'?MAX_PIXEL_CELLS:MAX_GLYPH_CELLS;let cols=Math.max(1,Math.ceil(c.w/cell)),rows=Math.max(1,Math.ceil(c.h/(cell*aspect)));const total=cols*rows;if(total>limit){const k=Math.sqrt(total/limit);cell=Math.ceil(cell*k);cols=Math.ceil(c.w/cell);rows=Math.ceil(c.h/(cell*aspect))}return{cell,cellH:cell*aspect,cols,rows,total:cols*rows,limited:cell>(+c.cell||8)}}
  const B2=[[0,2],[3,1]],B4=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];
  function ditherDelta(x,y){if(art.dither==='none')return 0;if(art.dither==='noise')return (mulberry32(hash32(`${seedEl.value}|dither|${x}|${y}`))()-.5)*.12;const m=art.dither==='bayer2'?B2:B4,n=m.length,v=m[y%n][x%n],max=n*n;return((v+.5)/max-.5)*.18}
  function quant(v){const levels=Math.max(2,art.toneSteps);return clamp(Math.round(clamp(v,0,1)*(levels-1))/(levels-1),0,1)}
  function glyphString(mode){let chars=art.glyphSet==='custom'?(art.glyphChars||' .#@'):(glyphSets[art.glyphSet]||glyphSets.dense);if(mode==='braille')chars=glyphSets.braille;if(art.glyphInvert)chars=[...chars].reverse().join('');return chars||' .#@'}
  function glyphColor(br,r,g,b,pal,mode){if(mode==='ansi'||art.glyphColor==='source')return`rgb(${r},${g},${b})`;if(art.glyphColor==='palette')return pal[Math.min(pal.length-1,Math.floor(br*pal.length))];if(art.glyphColor==='green')return'#5cff79';if(art.glyphColor==='amber')return'#ffbf4a';if(art.glyphColor==='cyan')return'#62e6ff';return'#f3f4f6'}
  function drawPixelShape(x,y,w,h,color){const gap=Math.min(art.gap,Math.max(0,Math.min(w,h)/2-1)),xx=x+gap,yy=y+gap,ww=Math.max(1,w-gap*2),hh=Math.max(1,h-gap*2);sourceCtx.fillStyle=color;if(art.pixelShape==='circle'){sourceCtx.beginPath();sourceCtx.ellipse(xx+ww/2,yy+hh/2,ww/2,hh/2,0,0,Math.PI*2);sourceCtx.fill()}else if(art.pixelShape==='diamond'){sourceCtx.beginPath();sourceCtx.moveTo(xx+ww/2,yy);sourceCtx.lineTo(xx+ww,yy+hh/2);sourceCtx.lineTo(xx+ww/2,yy+hh);sourceCtx.lineTo(xx,yy+hh/2);sourceCtx.closePath();sourceCtx.fill()}else if(art.pixelShape==='hline')sourceCtx.fillRect(xx,yy+hh*.38,ww,Math.max(1,hh*.24));else if(art.pixelShape==='vline')sourceCtx.fillRect(xx+ww*.38,yy,Math.max(1,ww*.24),hh);else if(art.pixelShape==='cross'){sourceCtx.fillRect(xx,yy+hh*.38,ww,Math.max(1,hh*.24));sourceCtx.fillRect(xx+ww*.38,yy,Math.max(1,ww*.24),hh)}else sourceCtx.fillRect(xx,yy,ww,hh)}
  function enhancedRender(c,desired){const grid=effectiveCell(c,desired),pal=paletteFor({...c,mode:'pixel'});sample.width=grid.cols;sample.height=grid.rows;sctx.imageSmoothingEnabled=true;sctx.drawImage(sourceCanvas,0,0,grid.cols,grid.rows);const d=sctx.getImageData(0,0,grid.cols,grid.rows).data,chars=glyphString(desired);sourceCtx.save();sourceCtx.setTransform(1,0,0,1,0,0);sourceCtx.globalCompositeOperation='source-over';sourceCtx.globalAlpha=1;sourceCtx.clearRect(0,0,c.w,c.h);if(desired!=='pixel'){sourceCtx.fillStyle=art.asciiBg;sourceCtx.fillRect(0,0,c.w,c.h);sourceCtx.font=`${Math.max(5,grid.cell*.9)}px ui-monospace,SFMono-Regular,Consolas,monospace`;sourceCtx.textBaseline='top'}for(let y=0;y<grid.rows;y++)for(let x=0;x<grid.cols;x++){const i=(y*grid.cols+x)*4,r=d[i],g=d[i+1],b=d[i+2],raw=(r+g+b)/765,br=quant(raw+ditherDelta(x,y)),px=x*grid.cell,py=y*grid.cellH;if(desired==='pixel'){const q=Math.round(br*(art.toneSteps-1))/(art.toneSteps-1),mix=art.toneSteps<=4?pal[Math.min(pal.length-1,Math.floor(q*pal.length))]:`rgb(${Math.round(r*q/raw||0)},${Math.round(g*q/raw||0)},${Math.round(b*q/raw||0)})`;drawPixelShape(px,py,grid.cell,grid.cellH,mix)}else{const idx=Math.min(chars.length-1,Math.floor(br*(chars.length-1))),ch=chars[idx]||' ';if(desired==='hybrid'){sourceCtx.fillStyle=pal[Math.min(pal.length-1,Math.floor(br*pal.length))];sourceCtx.fillRect(px,py,grid.cell,grid.cellH);sourceCtx.fillStyle=br>.55?'#fff':'#05070a'}else sourceCtx.fillStyle=glyphColor(br,r,g,b,pal,desired);sourceCtx.fillText(ch,px,py)}}sourceCtx.restore();const out=byId('artReadout');if(out)out.textContent=`${grid.cols}×${grid.rows} cells · cell ${grid.cell}${grid.limited?' (auto-limited)':''}`;const status=byId('webStatus');if(status)status.textContent=`${desired} · ${c.engine} · ${c.w}×${c.h} · ${grid.total.toLocaleString()} cells`}

  function clearSource(c,color='#05070b'){if(sourceCanvas.width!==c.w||sourceCanvas.height!==c.h){sourceCanvas.width=c.w;sourceCanvas.height=c.h}sourceCtx.setTransform(1,0,0,1,0,0);sourceCtx.globalCompositeOperation='source-over';sourceCtx.globalAlpha=1;sourceCtx.fillStyle=color;sourceCtx.fillRect(0,0,c.w,c.h)}
  function drawMaze(c,time){clearSource(c,'#06100e');const pal=paletteFor(c),cell=Math.max(8,c.cell*2,Math.ceil(Math.sqrt(c.w*c.h/12000))),cols=Math.ceil(c.w/cell),rows=Math.ceil(c.h/cell),r=mulberry32(hash32(`${c.seed}|maze|${Math.floor(motionTime(c,time))}`));sourceCtx.strokeStyle=pal[3];sourceCtx.lineWidth=Math.max(1,cell*.14);sourceCtx.beginPath();for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=x*cell,py=y*cell;if(x===0||r()>.48){sourceCtx.moveTo(px,py);sourceCtx.lineTo(px,py+cell)}if(y===0||r()>.48){sourceCtx.moveTo(px,py);sourceCtx.lineTo(px+cell,py)}}sourceCtx.stroke();sourceCtx.fillStyle=pal[1];for(let i=0;i<Math.max(3,Math.floor(cols*rows/80));i++)sourceCtx.fillRect(Math.floor(r()*cols)*cell+cell*.32,Math.floor(r()*rows)*cell+cell*.32,cell*.36,cell*.36)}
  function drawIsometric(c,time){clearSource(c,'#070912');const pal=paletteFor(c),cell=Math.max(12,c.cell*3),tw=cell*2,th=cell,r=mulberry32(hash32(`${c.seed}|iso`)),t=motionTime(c,time);for(let gy=-2;gy<c.h/th+3;gy++)for(let gx=-2;gx<c.w/tw+3;gx++){const cx=gx*tw+(gy%2)*cell+cell,cy=gy*th*.7+cell,h=(.2+r()*.8)*cell*(1+.18*Math.sin(t+gx*.5+gy*.35));sourceCtx.fillStyle=pal[(gx+gy+99)%pal.length];sourceCtx.beginPath();sourceCtx.moveTo(cx,cy-h);sourceCtx.lineTo(cx+cell,cy-h+th*.5);sourceCtx.lineTo(cx,cy-h+th);sourceCtx.lineTo(cx-cell,cy-h+th*.5);sourceCtx.closePath();sourceCtx.fill();sourceCtx.strokeStyle='#0007';sourceCtx.stroke()}}
  function drawPlasma(c,time){clearSource(c);const pal=paletteFor(c),cell=Math.max(2,c.cell),t=motionTime(c,time);for(let y=0;y<c.h;y+=cell)for(let x=0;x<c.w;x+=cell){const u=x/c.w,v=y/c.h,q=(Math.sin(u*18+t)+Math.sin(v*23-t*.7)+Math.sin((u+v)*31+t*.35)+Math.cos(Math.hypot(u-.5,v-.5)*42-t))/4,n=(q+1)/2;sourceCtx.fillStyle=pal[Math.min(pal.length-1,Math.floor(n*pal.length))];sourceCtx.fillRect(x,y,cell,cell)}}
  function drawVoronoi(c,time){clearSource(c);const pal=paletteFor(c),cell=Math.max(4,c.cell),count=24,r=mulberry32(hash32(`${c.seed}|voronoi`)),t=motionTime(c,time),pts=Array.from({length:count},(_,i)=>({x:(r()*.9+.05)*c.w+Math.sin(t*.2+i)*c.w*.015,y:(r()*.9+.05)*c.h+Math.cos(t*.17+i)*c.h*.015,p:i%pal.length}));for(let y=0;y<c.h;y+=cell)for(let x=0;x<c.w;x+=cell){let best=Infinity,idx=0;for(let i=0;i<pts.length;i++){const dx=x-pts[i].x,dy=y-pts[i].y,d=dx*dx+dy*dy;if(d<best){best=d;idx=i}}sourceCtx.fillStyle=pal[pts[idx].p];sourceCtx.fillRect(x,y,cell,cell)}}
  function drawInterference(c,time){clearSource(c);const pal=paletteFor(c),cell=Math.max(3,c.cell),t=motionTime(c,time),pts=[[.28+.05*Math.sin(t*.4),.35],[.72,.38+.05*Math.cos(t*.31)],[.5,.72]];for(let y=0;y<c.h;y+=cell)for(let x=0;x<c.w;x+=cell){let q=0;for(const [px,py] of pts)q+=Math.sin(Math.hypot(x/c.w-px,y/c.h-py)*54-t*2.2);const n=(q/pts.length+1)/2;sourceCtx.fillStyle=pal[Math.min(pal.length-1,Math.floor(n*pal.length))];sourceCtx.fillRect(x,y,cell,cell)}}
  function customEngine(c,time){if(c.engine==='maze')drawMaze(c,time);else if(c.engine==='isometric')drawIsometric(c,time);else if(c.engine==='plasma')drawPlasma(c,time);else if(c.engine==='voronoi')drawVoronoi(c,time);else if(c.engine==='interference')drawInterference(c,time);else return false;return true}

  generateSource=function(time=0){const desired=genMode.value,c=generatorConfig();readArt();try{genMode.value='pixel';const custom=customEngine({...c,mode:'pixel'},time);if(!custom)priorGenerateSource(time);genMode.value=desired;enhancedRender({...c,mode:desired},desired)}catch(err){genMode.value=desired;console.error('Enhanced renderer failed',err);toast(`Renderer fallback: ${err.message}`);try{priorGenerateSource(time)}catch(e){console.error(e)}}};

  function bind(){
    loadLocal();injectUI();writeArt();applyCompact();applyTab(state.tab);
    byId('compactToggle')?.addEventListener('click',()=>{state.compact=!state.compact;applyCompact()});document.querySelectorAll('[data-webtab]').forEach(b=>b.addEventListener('click',()=>applyTab(b.dataset.webtab)));
    ['pixelShape','toneSteps','artDither','pixelGap','glyphSet','glyphChars','glyphColor','glyphAspect','asciiBg','glyphInvert'].forEach(id=>byId(id)?.addEventListener('input',()=>{readArt();if(media==='generated')renderStaticIfNeeded()}));
    byId('artResetBtn')?.addEventListener('click',resetArt);byId('artRandomBtn')?.addEventListener('click',randomizeArt);byId('structureQuick')?.addEventListener('change',e=>{if(!e.target.value)return;genEngine.value=e.target.value;startGenerated();e.target.value=''});
    genMode.addEventListener('change',()=>{if(genMode.value==='braille'){art.glyphSet='braille';art.glyphColor='mono';writeArt()}else if(genMode.value==='ansi'){art.glyphColor='source';writeArt()}});
    window.circuitbendWebview={exportState:()=>({compact:state.compact,tab:state.tab,art:{...art}}),importState:x=>{if(!x)return;if(x.art)Object.assign(art,x.art);if(typeof x.compact==='boolean')state.compact=x.compact;if(x.tab)state.tab=x.tab;writeArt();applyCompact();applyTab(state.tab);renderStaticIfNeeded()},resetArt,randomizeArt};
    if(media==='none'){genEngine.value='maze';genMode.value='pixel';promptEl.value='circuit maze, high contrast, readable pathways';seedEl.value='circuitbend';startGenerated()}
  }
  if(document.readyState==='complete')bind();else window.addEventListener('load',bind,{once:true});
})();
