import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../main.js',import.meta.url),'utf8');
const project=fs.readFileSync(new URL('../project.js',import.meta.url),'utf8');
const advanced=fs.readFileSync(new URL('../advanced.js',import.meta.url),'utf8');
new Function(js);
new Function(project);
new Function(advanced);
const htmlIds=new Set([...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]));
const referenced=[...js.matchAll(/\$\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const projectRefs=[...project.matchAll(/getElementById\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const advancedRefs=[...advanced.matchAll(/(?:byId|document\.getElementById)\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const missing=[...new Set([...referenced,...projectRefs,...advancedRefs].filter(id=>!htmlIds.has(id)))];
if(missing.length)throw new Error(`Missing DOM ids referenced by scripts: ${missing.join(', ')}`);
for(const required of ['canvas','sourceCanvas','prompt','generateBtn','recordBtn','controls','projectSaveBtn','projectFile','sourcePreset','sizePreset','renderBudget','paletteMode','overlayEnabled','effectSearch','activeEffects','exportFullBtn'])if(!htmlIds.has(required))throw new Error(`Required sandbox element missing: ${required}`);
for(const marker of ['function generateSource','function drawMath','function drawCellular','function toggleRecording','function effectiveState'])if(!js.includes(marker))throw new Error(`Core feature missing: ${marker}`);
for(const marker of ['circuitbend-project','projectState','restoreProject','circuitbendAdvanced'])if(!project.includes(marker))throw new Error(`Project feature missing: ${marker}`);
for(const marker of ['drawCalibration','drawWaveform','drawMandala','drawTextSheet','drawNoise','drawOverlay','exportFullResolution','sourcePresets','randomizeGroup','renderActiveEffects','window.circuitbendAdvanced'])if(!advanced.includes(marker))throw new Error(`Advanced feature missing: ${marker}`);
for(const engine of ['gradient','primitives','calibration','waveform','mandala','textsheet','noise'])if(!html.includes(`value="${engine}"`))throw new Error(`Source engine option missing: ${engine}`);
if(!html.includes('max="4096"'))throw new Error('Scalable 4096px source dimensions not exposed');
console.log(`Smoke OK: ${htmlIds.size} DOM ids, ${referenced.length+projectRefs.length+advancedRefs.length} script id references, core + advanced source/scaling/configuration/project IO present.`);
