import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../main.js',import.meta.url),'utf8');
const project=fs.readFileSync(new URL('../project.js',import.meta.url),'utf8');
const advanced=fs.readFileSync(new URL('../advanced.js',import.meta.url),'utf8');
const webview=fs.readFileSync(new URL('../webview.js',import.meta.url),'utf8');
const mathlab=fs.readFileSync(new URL('../mathlab.js',import.meta.url),'utf8');
const streamlined=fs.readFileSync(new URL('../streamlined.js',import.meta.url),'utf8');
const viewer=fs.readFileSync(new URL('../preview-window.js',import.meta.url),'utf8');
new Function(js);
new Function(project);
new Function(advanced);
new Function(webview);
new Function(mathlab);
new Function(streamlined);
new Function(viewer);
const htmlIds=new Set([...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]));
const referenced=[...js.matchAll(/\$\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const projectRefs=[...project.matchAll(/getElementById\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const advancedRefs=[...advanced.matchAll(/(?:byId|document\.getElementById)\(['"]([^'"]+)['"]\)/g)].map(m=>m[1]);
const missing=[...new Set([...referenced,...projectRefs,...advancedRefs].filter(id=>!htmlIds.has(id)))];
if(missing.length)throw new Error(`Missing DOM ids referenced by core scripts: ${missing.join(', ')}`);
for(const required of ['canvas','sourceCanvas','prompt','generateBtn','recordBtn','controls','projectSaveBtn','projectFile','sourcePreset','sizePreset','renderBudget','paletteMode','overlayEnabled','effectSearch','activeEffects','exportFullBtn'])if(!htmlIds.has(required))throw new Error(`Required sandbox element missing: ${required}`);
for(const marker of ['function generateSource','function drawMath','function drawCellular','function toggleRecording','function effectiveState'])if(!js.includes(marker))throw new Error(`Core feature missing: ${marker}`);
for(const marker of ['circuitbend-project','projectState','restoreProject','circuitbendAdvanced','circuitbendWebview','circuitbendMath','circuitbendWorkspace','circuitbendViewer','webview.js','mathlab.js','streamlined.js','preview-window.js'])if(!project.includes(marker))throw new Error(`Project/web loader feature missing: ${marker}`);
for(const marker of ['drawCalibration','drawWaveform','drawMandala','drawTextSheet','drawNoise','drawOverlay','exportFullResolution','sourcePresets','randomizeGroup','renderActiveEffects','window.circuitbendAdvanced'])if(!advanced.includes(marker))throw new Error(`Advanced feature missing: ${marker}`);
for(const marker of ['enhancedRender','effectiveCell','drawMaze','drawIsometric','drawPlasma','drawVoronoi','drawInterference','glyphSets','MAX_GLYPH_CELLS','window.circuitbendWebview','compactView'])if(!webview.includes(marker))throw new Error(`Web-view feature missing: ${marker}`);
for(const marker of ['renderField','renderEscape','renderNewton','renderDomain','renderChladni','trajectory','renderClifford','renderDeJong','renderLorenz','renderLissajous','renderHarmonograph','renderSuperformula','renderRose','renderModular','renderPhyllotaxis','renderLogistic','renderUlam','renderHilbert','renderSierpinski','postProcess','window.circuitbendMath'])if(!mathlab.includes(marker))throw new Error(`Math Lab feature missing: ${marker}`);
for(const marker of ['streamBar','taskTabs','quickMake','setTask','applyFocus','previewPinned','moveSecondaryActions','window.circuitbendWorkspace'])if(!streamlined.includes(marker))throw new Error(`Streamlined workspace feature missing: ${marker}`);
for(const marker of ['sourceInfo','viewerFloating','buildPopup','window.open','ResizeObserver','renderMirrors','Imported image/video','window.circuitbendViewer'])if(!viewer.includes(marker))throw new Error(`Pop-out viewer feature missing: ${marker}`);
for(const task of ['create','math','style','fx','export'])if(!streamlined.includes(`${task}:`))throw new Error(`Task workspace missing: ${task}`);
for(const engine of ['gradient','primitives','calibration','waveform','mandala','textsheet','noise'])if(!html.includes(`value="${engine}"`))throw new Error(`Source engine option missing: ${engine}`);
for(const engine of ['maze','isometric','plasma','voronoi','interference'])if(!webview.includes(`'${engine}'`))throw new Error(`Enhanced source engine missing: ${engine}`);
for(const engine of ['mandelbrot','julia','newton','burningship','domain','chladni','clifford','dejong','henon','lorenz','lissajous','harmonograph','superformula','rose','modular','phyllotaxis','logistic','ulam','hilbert','sierpinski'])if(!mathlab.includes(`${engine}:`)&&!mathlab.includes(`'${engine}'`))throw new Error(`Mathematical source engine missing: ${engine}`);
for(const mode of ['ansi','braille'])if(!webview.includes(`'${mode}'`))throw new Error(`Enhanced render mode missing: ${mode}`);
if(!html.includes('max="4096"'))throw new Error('Scalable 4096px source dimensions not exposed');
if(!mathlab.includes('FIELD_BUDGET')||!mathlab.includes('POINT_CAP'))throw new Error('Math render performance guardrails missing');
console.log(`Smoke OK: ${htmlIds.size} static DOM ids; core + advanced + pixel/ASCII + Math Lab + streamlined workspace + freely resizable pop-out viewer/project IO parse and feature checks passed.`);
